export const DANG_NHAP_BAT_DAU = "DANG_NHAP_BAT_DAU";
export const DANG_NHAP_THANH_CONG = "DANG_NHAP_THANH_CONG";
export const DANG_NHAP_THAT_BAI = "DANG_NHAP_THAT_BAI";

export const TRUY_CAP_VALID_CODE_BAT_DAU = "TRUY_CAP_VALID_CODE_BAT_DAU";
export const TRUY_CAP_VALID_CODE_THANH_CONG = "TRUY_CAP_VALID_CODE_THANH_CONG";
export const TRUY_CAP_VALID_CODE_THAT_BAI = "TRUY_CAP_VALID_CODE_THAT_BAI";

export const TRUY_CAP_LOGIN_TK88_BAT_DAU = "TRUY_CAP_LOGIN_TK88_BAT_DAU";
export const TRUY_CAP_LOGIN_TK88_THANH_CONG = "TRUY_CAP_LOGIN_TK88_THANH_CONG";
export const TRUY_CAP_LOGIN_TK88_THAT_BAI = "TRUY_CAP_LOGIN_TK88_THAT_BAI";
export const TRUY_CAP_THONG_TIN_NGUOI_DUNG_BAT_DAU =
  "TRUY_CAP_THONG_TIN_NGUOI_DUNG_BAT_DAU";
export const TRUY_CAP_THONG_TIN_NGUOI_DUNG_THANH_CONG =
  "TRUY_CAP_THONG_TIN_NGUOI_DUNG_THANH_CONG";
export const TRUY_CAP_THONG_TIN_NGUOI_DUNG_THAT_BAI =
  "TRUY_CAP_THONG_TIN_NGUOI_DUNG_THAT_BAI";
